rabbitmq:
  container_name: monitor-rabbitmq
  image: "rabbitmq:3.6.6-management"
  restart: always
  ports:
    - 5672:5672 # port for the daemon API, can be exposed to public.
    - 15672:15672 # port for the Management interface
  volumes:
    - ./definitions.json:/etc/rabbitmq/definitions.json
    - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
